### ISSUE TITLE
Detect true Cassandra server being contacted (RemoteHost/RemotePort)

### ISSUE THREAD

**Issue by pglombardo** [appneta/ruby-traceview#4]
The Ruby Cassandra instrumentation incorrectly reports the first cassandra in the server list - not the actual one that is servicing the query.

https://github.com/appneta/oboe-ruby/blob/master/lib/oboe/inst/cassandra.rb#L16

We should be able to determine the specific cassandra server in use and instead report that.

**Comment by pglombardo** [comment]
Will not fix (until any situation change occurs).

**Comment by dankosaur** [comment]
This seems like a relevant concern for our `RemoteHost` KV audit... cc @ashish-kakran @MikeA-

**Comment by MikeA-** [comment]
agreed seems important.  @pglombardo what situation change are you referring to?

**Comment by pglombardo** [comment]
This issue has been open for [2-3 years](https://github.com/tracelytics/oboe-ruby/issues/107) and has never percolated to the top of the task list.  We had it in Github as it was low hanging fruit for any public contributed fixes (hint hint public!) but it never materialized.

This is still in Jira (TVI-415) - the GH issue is unnecessary if it's just going to sit here for another couple years.
